export const THEMES = {
  default: {
    primary_Body_bg: '#F2F4F7',
    secondary_Body_bg: '#fbfcfd',
    filter_strip_bg: '#e8f7fe',
    filter_Bg: '#f4f9fb',
    pax_bg: '#dff4fe',
    travelAdvice_Bg: '#fff7eb',
    results_strip_Bg: 'rgba(29,178,245,.04)',
    flight_selected_Bg: '#EFFBFF ',
    more_flight_selected_Bg: '#e8f7fe',
    more_flight_bg: '#D0D5DD',
    sorting_card_active_bg: '#e5f7ff',
    price_sec_active_bg: '#cce9fa',

    bm_flight_review_bg: '#fafcfc',
    bm_name_reqmt_strip_bg: '#fff7eb',
    bm_meal_pref_active_bg: '#1db2f5',
    bm_checkIN_bag_bg: '#f4f7fc',

    payment_card: 'linear-gradient(28deg, #1e3845 6%, #094862 95%)',
    payment_card_strip: '#1e3945',
    payment_card_border: '#158fc4',

    text_primary_color: '#062231',
    text_secondary_color: '#1db2f5',
    text_info_color: '#6d7a83',
    text_link_color: '#1db2f5',
    text_warning_color: '#CE7E07',
    text_success_color: '#2aa04a',
    text_danger_color: '#f51b46',
    text_color_new: '#052231',
    text_white_color: '#ffffff',

    primary_btn_bg: '#1db2f5',
    success_btn_bg: '#15c4a1',
    btn_outline_col: '#1db2f5',

    primaryBgColor: '#062231',
    secondaryBgColor: '#1db2f5',
    dangerBgColor: '#fee8ec',
    productsBgColor: '#E0F3FE',

    border_radius: '8px',
    border_default_color: '#e7e8ea',
    border_light_color: '#f2f4f3',
    border_active_color: '#1db2f5',
    border_input_color: '#a7afc0',
    border_input_focus_color: '#687189',

    seatmap_seat_Selected: '#20be79',
    seatmap_seat_Available: '#76d1f9',
    seatmap_seat_Occupied: '#5197eb',
    seatmap_seat_Blocked: '#fdd700',
    seatmap_notseat: '#c1c3c8',

    search_sec_boxshadow: '0 0 4px 0 rgb(0 0 0 / 20%)',
    flight_recommended_label_bg: '#DDE0FF',
    flight_recommended_label_color: '#532BD7',
    flight_cheapest_label_bg: '#DCFAE6',
    flight_cheapest_label_color: '#067647',
    flight_fastest_label_bg: '#EAECF5',
    flight_fastest_label_color: '#363F72',
    new_UI_active_color: '#00C2F0',
    new_UI_active_text_color: '#00A1D4',
    layover_bg_color: '#FFFAEB',
    layover_text_color: '#B54708',
    label_color: '#667085',
    body_bg_clr: '#F2F4F7',
    //My-Account-Section
    myAccount_header_Bg: 'linear-gradient(180deg, #052231 100%, #052231 100%)'
  },
  investec: {
    primary_Body_bg: '#f7f6f5',
    secondary_Body_bg: '#fbfcfd',
    filter_strip_bg: '#ededea',
    filter_Bg: '#f7f6f5',
    pax_bg: '#ededea',
    travelAdvice_Bg: '#4b5160',
    results_strip_Bg: '#e4e3df',
    flight_selected_Bg: '#fcf2e7',
    more_flight_selected_Bg: '#fcf2e7',
    more_flight_bg: '#f4f4f2',
    sorting_card_active_bg: '#fcf2e7',
    price_sec_active_bg: '#fdead6',

    bm_flight_review_bg: '#f7f6f5',
    bm_name_reqmt_strip_bg: '#f0efed',
    bm_meal_pref_active_bg: '#323848',
    bm_checkIN_bag_bg: '#fcf2e7',

    payment_card: 'linear-gradient(28deg, #242B39 6%, #242B39 95%)',
    payment_card_strip: '#4b5160',
    payment_card_border: '#4b5160',

    text_primary_color: '#242b39',
    text_secondary_color: '#1db2f5',
    text_info_color: '#6e7480',
    text_link_color: '#ae6425',
    text_warning_color: '#CE7E07',
    text_success_color: '#449D48',
    text_danger_color: '#f51b46',
    text_color_new: '#052231',
    text_white_color: '#ffffff',

    primary_btn_bg: '#303849',
    success_btn_bg: '#303849',
    btn_outline_col: '#ae6425',

    primaryBgColor: '#242b39',
    secondaryBgColor: '#000000',
    dangerBgColor: '#fee8ec',
    productsBgColor: '#e4e3df',

    border_radius: '50px',
    border_default_color: '#e7e8ea',
    border_light_color: '#f2f4f3',
    border_active_color: '#ae6425',
    border_input_color: '#C1C3C8',
    border_input_focus_color: '#687189',

    seatmap_seat_Selected: '#303849',
    seatmap_seat_Available: '#c2dadc',
    seatmap_seat_Occupied: '#CD934D',
    seatmap_seat_Blocked: '#f2e5d5',
    seatmap_notAseat: '#c1c3c8',

    search_sec_boxshadow: 'none',
    flight_recommended_label_bg: '#DDE0FF',
    flight_recommended_label_color: '#532BD7',
    flight_cheapest_label_bg: '#DCFAE6',
    flight_cheapest_label_color: '#067647',
    flight_fastest_label_bg: '#EAECF5',
    flight_fastest_label_color: '#363F72',
    new_UI_active_color: '#1db2f5',
    new_UI_active_text_color: '#ae6425',
    layover_bg_color: '#FFFAEB',
    layover_text_color: '#B54708',
    label_color: '#667085',
    body_bg_clr: '#f5f7fa',
    //My-Account-Section
    myAccount_header_Bg: 'linear-gradient(180deg, #052231 100%, #052231 100%)'
  },
  gigm: {
    primary_Body_bg: '#f5f8ff',
    secondary_Body_bg: '#fbfcfd',
    filter_strip_bg: '#e8f7fe',
    filter_Bg: '#f4f9fb',
    pax_bg: '#dff4fe',
    travelAdvice_Bg: '#fff7eb',
    results_strip_Bg: 'rgba(29,178,245,.04)',
    flight_selected_Bg: '#dcf5fd',
    more_flight_selected_Bg: '#e8f7fe',
    more_flight_bg: '#737b8c',
    sorting_card_active_bg: '#e5f7ff',
    price_sec_active_bg: '#dcf5fd',

    bm_flight_review_bg: '#d0d5dd',
    bm_name_reqmt_strip_bg: '#fff7eb',
    bm_meal_pref_active_bg: '#1db2f5',
    bm_checkIN_bag_bg: '#f2fcf3',

    payment_card: 'linear-gradient(28deg, #1e3845 6%, #094862 95%)',
    payment_card_strip: '#021218',
    payment_card_border: '#158fc4',

    text_primary_color: '#021218',
    text_secondary_color: '#1db2f5',
    text_info_color: '#737b8c',
    text_link_color: '#e21d00',
    text_warning_color: '#CE7E07',
    text_success_color: '#20be79',
    text_danger_color: '#f51b46',
    text_color_new: '#021218',
    text_white_color: '#ffffff',

    primary_btn_bg: '#e21d00',
    success_btn_bg: '#15c4a1',
    btn_outline_col: '#1db2f5',

    primaryBgColor: '#062231',
    secondaryBgColor: '#1db2f5',
    dangerBgColor: '#fee8ec',
    productsBgColor: '#E0F3FE',

    border_radius: '3px',
    border_default_color: '#e7e8ea',
    border_light_color: '#f2f4f3',
    border_active_color: '#e21d00',
    border_input_color: '#737b8c',

    seatmap_seat_Selected: '#20be79',
    seatmap_seat_Available: '#76d1f9',
    seatmap_seat_Occupied: '#5197eb',
    seatmap_seat_Blocked: '#fdd700',
    seatmap_notseat: '#c1c3c8',

    search_sec_boxshadow: '0 0 4px 0 rgb(0 0 0 / 20%)',
    flight_recommended_label_bg: '#DDE0FF',
    flight_recommended_label_color: '#532BD7',
    flight_cheapest_label_bg: '#DCFAE6',
    flight_cheapest_label_color: '#067647',
    flight_fastest_label_bg: '#EAECF5',
    flight_fastest_label_color: '#363F72',
    new_UI_active_color: '#e21d00',
    new_UI_active_text_color: '#e21d00',
    layover_bg_color: '#FFFAEB',
    layover_text_color: '#B54708',
    label_color: '#737B8C',
    body_bg_clr: '#f4f5f7',
    //My-Account-Section
    myAccount_header_Bg: 'linear-gradient(180deg, #052231 100%, #052231 100%)'
  },
  clubhub: {
    primary_Body_bg: '#F2F4F7',
    secondary_Body_bg: '#fbfcfd',
    filter_strip_bg: '#F3F5F7',
    filter_Bg: '#f4f9fb',
    pax_bg: '#dff4fe',
    travelAdvice_Bg: '#fff7eb',
    results_strip_Bg: 'rgba(29,178,245,.04)',
    flight_selected_Bg: '#FFF6F6 ',
    more_flight_selected_Bg: '#e8f7fe',
    more_flight_bg: '#D0D5DD',
    sorting_card_active_bg: '#e5f7ff',
    price_sec_active_bg: '#cce9fa',

    bm_flight_review_bg: '#fafcfc',
    bm_name_reqmt_strip_bg: '#F3F5F7',
    bm_meal_pref_active_bg: '#9D1F22',
    bm_checkIN_bag_bg: '#f3f5f7',

    payment_card: 'linear-gradient(28deg, #5B616E 6%, #030000 95%)',
    payment_card_strip: '#1e3945',
    payment_card_border: '#158fc4',

    text_primary_color: '#030000',
    text_secondary_color: '#9D1F22',
    text_info_color: '#6d7a83',
    text_link_color: '#9D1F22',
    text_warning_color: '#CE7E07',
    text_success_color: '#2aa04a',
    text_danger_color: '#f51b46',
    text_white_color: '#ffffff',

    primary_btn_bg: '#9D1F22',
    success_btn_bg: '#15c4a1',
    btn_outline_col: '#9D1F22',

    primaryBgColor: '#062231',
    secondaryBgColor: '#9D1F22',
    dangerBgColor: '#fee8ec',
    productsBgColor: '#F3F5F7',

    border_radius: '8px',
    border_default_color: '#BCBEC0',
    border_light_color: '#f2f4f3',
    border_active_color: '#9D1F22',
    border_input_color: '#BCBEC0',
    border_input_focus_color: '#687189',

    seatmap_seat_Selected: '#20be79',
    seatmap_seat_Available: '#76d1f9',
    seatmap_seat_Occupied: '#5197eb',
    seatmap_seat_Blocked: '#fdd700',
    seatmap_notseat: '#c1c3c8',

    search_sec_boxshadow: '0 0 4px 0 rgb(0 0 0 / 20%)',
    flight_recommended_label_bg: '#DDE0FF',
    flight_recommended_label_color: '#532BD7',
    flight_cheapest_label_bg: '#DCFAE6',
    flight_cheapest_label_color: '#067647',
    flight_fastest_label_bg: '#EAECF5',
    flight_fastest_label_color: '#363F72',
    new_UI_active_color: '#9D1F22',
    new_UI_active_text_color: '#9D1F22',
    layover_bg_color: '#FFFAEB',
    layover_text_color: '#B54708',
    label_color: '#667085',
    body_bg_clr: '#E9ECEF',
    //My-Account-Section
    myAccount_header_Bg: 'linear-gradient(180deg, #052231 100%, #052231 100%)'
  },
  momentum: {
    secondary_Body_bg: '#fbfcfd',
    filter_strip_bg: '#e8f7fe',
    filter_Bg: '#f4f9fb',
    pax_bg: '#dff4fe',
    travelAdvice_Bg: '#fff7eb',
    results_strip_Bg: 'rgba(29,178,245,.04)',
    flight_selected_Bg: '#FFEBF0 ',
    more_flight_selected_Bg: '#e8f7fe',
    more_flight_bg: '#D0D5DD',
    sorting_card_active_bg: '#e5f7ff',
    price_sec_active_bg: '#cce9fa',

    bm_flight_review_bg: '#fafcfc',
    bm_name_reqmt_strip_bg: '#edf1f9',
    bm_meal_pref_active_bg: '#1db2f5',
    bm_checkIN_bag_bg: '#f4f7fc',

    payment_card: 'linear-gradient(28deg, #1e3845 6%, #094862 95%)',
    payment_card_strip: '#1e3945',
    payment_card_border: '#158fc4',

    text_primary_color: '#001330',
    text_secondary_color: '#1db2f5',
    text_info_color: '#748093',
    text_link_color: '#ED1C24',
    text_warning_color: '#CE7E07',
    text_success_color: '#2aa04a',
    text_danger_color: '#f51b46',
    text_color_new: '#001330',
    text_white_color: '#ffffff',

    primary_btn_bg: '#ED1C24',
    success_btn_bg: '#15c4a1',
    btn_outline_col: '#fff',

    primaryBgColor: '#062231',
    secondaryBgColor: '#1db2f5',
    dangerBgColor: '#fee8ec',
    productsBgColor: '#EAECF2',

    border_radius: '8px',
    border_default_color: '#e7e8ea',
    border_light_color: '#f2f4f3',
    border_active_color: '#ED1C24',
    border_input_color: '#909AAE',
    border_input_focus_color: '#687189',

    seatmap_seat_Selected: '#20be79',
    seatmap_seat_Available: '#76d1f9',
    seatmap_seat_Occupied: '#5197eb',
    seatmap_seat_Blocked: '#fdd700',
    seatmap_notseat: '#c1c3c8',

    search_sec_boxshadow: '0 0 4px 0 rgb(0 0 0 / 20%)',
    flight_recommended_label_bg: '#DDE0FF',
    flight_recommended_label_color: '#532BD7',
    flight_cheapest_label_bg: '#DCFAE6',
    flight_cheapest_label_color: '#067647',
    flight_fastest_label_bg: '#EAECF5',
    flight_fastest_label_color: '#363F72',
    new_UI_active_color: '#ED1C24',
    new_UI_active_text_color: '#ED1C24',
    layover_bg_color: '#FFFAEB',
    layover_text_color: '#B54708',
    label_color: '#748093',
    body_bg_clr: '#F2F4F7',
    //My-Account-Section
    myAccount_header_Bg: 'linear-gradient(0deg, rgba(157,154,255,1) 0%, rgba(89,85,228,1) 60%)',
  },
  absa: {
    secondary_Body_bg: '#fbfcfd',
    filter_strip_bg: '#ffe2e8',
    filter_Bg: '#f4f9fb',
    pax_bg: '#dff4fe',
    travelAdvice_Bg: '#fff7eb',
    results_strip_Bg: 'rgba(29,178,245,.04)',
    flight_selected_Bg: '#ffffff',
    more_flight_selected_Bg: '#e8f7fe',
    more_flight_bg: '#D0D5DD',
    sorting_card_active_bg: '#e5f7ff',
    price_sec_active_bg: '#eae8e8',

    bm_flight_review_bg: '#fafcfc',
    bm_name_reqmt_strip_bg: '#fdece4',
    bm_meal_pref_active_bg: '#1db2f5',
    bm_checkIN_bag_bg: '#F8F6F6',

    payment_card: 'linear-gradient(28deg, #1e3845 6%, #094862 95%)',
    payment_card_strip: '#1e3945',
    payment_card_border: '#158fc4',

    text_primary_color: '#001330',
    text_secondary_color: '#1db2f5',
    text_info_color: '#4C4949',
    text_link_color: '#F0325A',
    text_warning_color: '#CE7E07',
    text_success_color: '#168335',
    text_danger_color: '#910826',
    text_color_new: '#131010',
    text_white_color : '#ffffff',

    primary_btn_bg: '#F0325A',
    success_btn_bg: '#15c4a1',
    btn_outline_col: '#fff',

    primaryBgColor: '#062231',
    secondaryBgColor: '#1db2f5',
    dangerBgColor: '#FAD9E0',
    productsBgColor: '#fff',

    border_radius: '8px',
    border_default_color: '#e7e8ea',
    border_light_color: '#f2f4f3',
    border_active_color: '#ED1C24',
    border_input_color: '#F0325A',
    border_input_focus_color: '#687189',

    seatmap_seat_Selected: '#20be79',
    seatmap_seat_Available: '#76d1f9',
    seatmap_seat_Occupied: '#5197eb',
    seatmap_seat_Blocked: '#fdd700',
    seatmap_notseat: '#c1c3c8',

    search_sec_boxshadow: '0 0 4px 0 rgb(0 0 0 / 20%)',
    flight_recommended_label_bg: '#FAD9E0',
    flight_recommended_label_color: '#910826',
    flight_cheapest_label_bg: '#DCFAE6',
    flight_cheapest_label_color: '#067647',
    flight_fastest_label_bg: '#FDECE4',
    flight_fastest_label_color: '#87310F',
    warning_label_bg: '#FDECE4',
    warning_label_color: '#87310F',
    new_UI_active_color: '#F0325A',
    new_UI_active_text_color: '#2D2323',
    layover_bg_color: '#EDF5FD',
    layover_text_color: '#1F4D7A',
    label_color: '#748093',
    body_bg_clr: '#F8F6F6',
    //My-Account-Section
    myAccount_header_Bg: 'linear-gradient(0deg, #960528 0%, #960528 100%)',
  },
  standardbank: {
    primary_Body_bg: 'var(--sb_white)',
    secondary_Body_bg: 'var(--sb_background_bluegrey)',
    filter_strip_bg: '#BFDCFC',
    filter_Bg: '#f4f9fb',
    pax_bg: '#dff4fe',
    travelAdvice_Bg: '#fff7eb',
    results_strip_Bg: 'rgba(29,178,245,.04)',
    flight_selected_Bg: '#ffffff',
    more_flight_selected_Bg: 'none',
    more_flight_bg: 'var(--sb_background_bluegrey)',
    sorting_card_active_bg: '#e5f7ff',
    price_sec_active_bg: '#eae8e8',

    bm_flight_review_bg: '#fafcfc',
    bm_name_reqmt_strip_bg: 'var(--sb_lightorange)',
    bm_meal_pref_active_bg: '#1db2f5',
    bm_checkIN_bag_bg: '#F8F6F6',

    payment_card: 'linear-gradient(28deg, #1e3845 6%, #094862 95%)',
    payment_card_strip: '#1e3945',
    payment_card_border: '#158fc4',

    text_primary_color: 'var(--sb_darkgrey)',
    text_secondary_color: 'var(--sb_text_lightgrey)',
    text_info_color: 'var(--sb_text_lightgrey)',
    text_link_color: 'var(--sb_blue_link)',
    text_warning_color: 'var(--sb_orange)',
    text_success_color: '#168335',
    text_danger_color: 'var(--sb_red)',
    text_color_new: 'var(--sb_darkgrey)',
    text_white_color: '#ffffff',

    primary_btn_bg: 'var(--sb_blue_cta)',
    success_btn_bg: '#15c4a1',
    btn_outline_col: '#fff',

    primaryBgColor: '#FFFFFF',
    secondaryBgColor: 'var(--sb_text_lightgrey)',
    dangerBgColor: '#FAD9E0',
    productsBgColor: 'var(--sb_greyinfo)',

    border_radius: '8px',
    border_default_color: 'var(--sb_black_inputlines)',
    border_light_color: 'var(--sb_card_border_grey)',
    border_active_color: 'var(--sb_blue_cta)',
    border_input_color: 'var(--sb_card_border_grey)',
    border_input_focus_color: 'var(--sb_blue_dark)',

    seatmap_seat_Selected: '#20be79',
    seatmap_seat_Available: '#76d1f9',
    seatmap_seat_Occupied: '#5197eb',
    seatmap_seat_Blocked: '#fdd700',
    seatmap_notseat: '#c1c3c8',

    search_sec_boxshadow: '0 0 4px 0 rgb(0 0 0 / 20%)',
    flight_recommended_label_bg: '#F4F5FF',
    flight_recommended_label_color: '#0063E0',
    flight_cheapest_label_bg: '#F5F9F8',
    flight_cheapest_label_color: '#0A8D59',
    flight_fastest_label_bg: '#F7FAFF',
    flight_fastest_label_color: 'var(--sb_midgrey)',
    warning_label_bg: 'var(--sb-lightorange)',
    warning_label_color: 'var(--sb_black_sorta)',
    new_UI_active_color: 'var(--sb_blue_cta)', /* Selected flight card border */
    new_UI_active_text_color: 'var(--sb_black_pitchblack)',
    layover_bg_color: '#D9EFFF',
    layover_text_color: 'var(--sb_darkgrey)',
    label_color: '#748093',
    body_bg_clr: 'var(--sb_background_bluegrey)',
    myAccount_header_Bg: 'linear-gradient(0deg, #00008C, #00008C)',

    // New variables (non-standard) that can be ported to other themes.
    // NB: set fallback values where they are used for backwards-compatability.
    input_font_size: 'var(--sb_input_font_size)',
    input_height: 'var(--sb_input_height)',
    body_font_family: 'var(--sb_body_font_family)',
    heading_font_family: 'var(--sb_heading_font_family)',
    secondary_font_family: 'var(--sb_secondary_font_family)',
    btn_font_family: 'var(--sb_btn_font_family)',
    btn_font_size: 'var(--sb_btn_font_size)',
    infoBgColor: 'var(--sb_greyinfo)',
    btn_disabled: 'var(--sb_black_disable)',
    text_info_dark: '#1F4D7A',
    text_black_color: 'var(--sb_black)',
    primary_btn_bg2: 'var(--sb_blue_cta)',
    flight_seats_label_bg: '#FFFCF7',
    flight_seats_label_color: '#FF8900',

    // Standard Bank variables
    sb_gradient: ' linear-gradient(to top, #0062e1, #0033aa)',
    sb_blue_link: '#033ECA',
    sb_blue_dark: '#0032A8',
    sb_blue_darker: '#022373',
    sb_blue_dp: '#03A',
    sb_lightred: '#FAE4E6',
    sb_red: '#93072C',
    sb_lightorange: '#FFFCF7',
    sb_orange: '#FF780F',
    sb_orangeyellow: '#FF8E05',
    sb_green: '#16A34A', /* "Standard Bank Discounts" */
    sb_white: '#FFFFFF',
    sb_darkgrey: '#010C1E', /* Figma: Stand-Black */
    sb_mediumgrey: '#C7C5C5',
    sb_midgrey: '#667085',
    sb_charcoal: '#4C4949', /* Search Results: "457 Results Found" */
    sb_greyinfo: '#F3F7FF',
    sb_black_sorta: '#101828',
    sb_black_pitchblack: '#00002F',
    sb_black_inputlines: '#5E6470',
    sb_black_disable: '#96969B', /* Figma: Stand-black-diasble */
    sb_black_disable2: '#CDD2D6', /* Figma: Stand-black-disable2 */
    sb_blue_cta: '#0161E1',
    sb_background_bluegrey: '#F2F6F9',
    sb_text_lightgrey: '#A1A3A6',
    sb_body_font_size: '16px',
    sb_label_font_size: '14px',
    sb_label_font_size_xs: '12px',
    sb_label_font_size_sm: '13px',
    sb_label_font_size_md: '16px',
    sb_label_font_size_lg: '18px',
    sb_input_font_size: '16px', /* 14px and 15px have sizing issues on mobile where the top of the font is cut off */
    sb_btn_font_size: '14px',
    sb_heading_font_size: '18px',
    sb_body_font_family: `'BentonSans Regular', sans-serif`,
    sb_secondary_font_family: `'Roboto', sans-serif`,
    sb_heading_font_family: `'BentonSans Medium', sans-serif`,
    sb_bold_font_family: `'BentonSans Cond Medium', sans-serif`,
    sb_btn_font_family: `'BentonSans Regular', sans-serif`,
    sb_btn_height: '40px',
    sb_btn_height_md: '42px',
    sb_btn_height_sm: '32px',
    sb_input_height: '48px',
    sb_card_border_grey: '#E0DFE4',
  }
};
