// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.
// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
// import { env } from './.env';
import packageJson from '../../package.json';

export const environment = {
  production: false,
  hmr: true,
  serverUrl: 'https://beta.travelstart.com',
  API_URL: 'https://beta-wapi.travelstart.com',
  defaultLanguage: 'en-ZA',
  appVersion: packageJson.version,
  supportedLanguages: [
    'en-GO',
    'en-NA',
    'en-ZA',
    'en-BH',
    'en-BW',
    'en-EG',
    'en-KE',
    'en-KW',
    'en-MA',
    'en-NG',
    'en-OM',
    'en-QA',
    'en-SA',
    'en-TZ',
    'en-TR',
    'en-AE',
    'en-ZW',
    'en-IB',
    'en-GI',
    'en-FS',
    'en-MM',
    'en-ABSA',
  ],
  // Strapi API
  strapiUrl: 'https://beta-strapi.travelstart.com/api',
  // BigQuery API
  bigQueryUrl: 'https://europe-west2-ts-dev-dataops-prod.cloudfunctions.net/cms?api_key=tXr0HiFpxT2vWBT',
  firebase: {
  apiKey: "AIzaSyBBg0vwu574qvfa9DtUqGLkpDKm7xLBWZE",
  authDomain: "travelstart-b2c.firebaseapp.com",
  databaseURL: "https://travelstart-b2c-default-rtdb.firebaseio.com",
  projectId: "travelstart-b2c",
  storageBucket: "travelstart-b2c.firebasestorage.app",
  messagingSenderId: "944782183574",
  appId: "1:944782183574:web:2e9add407d2d83fcba86b7",
  measurementId: "G-645FYX81MG",
  vapidKey: "BFIS2bJmBSKfvRu6IKFHgoYyPwEnZVxy6oOsbD-clo-zPxoq1wue0W-HGRawg7j4xwcKEnefWVYl6iNSn0pAguI" // This is important for web push
  }
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */