export const ITERABLE_DATA_LAYER_KEYS = {
  ADDITIONAL_FARES: 'additionalFares',
  AFFILIATE_ID: 'affiliateId',
  AIRLINE_NAME: 'airlineName',
  ARRIVAL_TIME: 'Arrival_Time',
  BANK_ACCOUNT_NO: 'bankAccountNo',
  BANK_ID: 'bankId',
  BIRTH_DATE: 'birthDate',
  BOOKING_REFERENCE: 'bookingReference',
  CABIN_CLASS: 'Class',
  CAMPAIGN_TYPE: 'campaignType',
  CARD_TYPE: 'Card_Type',
  CART_PRODUCTS: 'cartProducts',
  CATEGORY: 'Category',
  CITY_PAIR: 'cityPair',
  COUNTRY: 'Country',
  COUNTRY_CODE: 'countryCode',
  CURRENCY: 'Currency',
  DEPARTURE_TIME: 'Departure_Time',
  DEPART_DATE: 'Onward_Date',
  DESTINATION_AIPORT_CODE: 'destinationAirportCode',
  DESTINATION_CITY: 'To_City',
  DESTINATION_COUNTRY: 'To_Country_Name',
  DESTINATION_COUNTRY_IATA: 'To_Country_Code',
  DESTINATION_IATA: 'To_City_Code',
  DOMAIN: 'Domain',
  ECOMMERCE: 'ecommerce',
  EMAIL: 'Email',
  FIRST_NAME: 'firstName',
  FLIGHT_NUMBERS: 'flightNumbers',
  FLIGHT_PRICE: 'flightPrice',
  FLIGHT_SELECTED: 'flightSelected',
  GENDER: 'Gender',
  IBAN: 'iban',
  ITEMS_GOOGLE_FLIGHTS: 'itemsGoogleFlights',
  LANGUAGE: 'Language',
  LANGUAGE_CODE: 'languageCode',
  LAST_NAME: 'lastName',
  LOCALITY: 'Locality',
  LOGIN_TYPE: 'Login_Type',
  METHOD: 'method',
  MTN_CUSTOMER: 'mtnCustomer',
  ONWARD_AIRLINE_NAMES: 'onwardAirlineNames',
  ONWARD_DATE_WE: 'onwardDateWE',
  ONWARD_STOPS: 'onwardStops',
  ORIGIN_AIRPORT_CODE: 'originAirportCode',
  ORIGIN_CITY: 'From_City',
  ORIGIN_COUNTRY: 'From_Country_Name',
  ORIGIN_COUNTRY_IATA: 'From_Country_Code',
  ORIGIN_IATA: 'From_City_Code',
  PAYMENT_METHOD_NAME: 'Payment_Method_name',
  PAYMENT_NAME: 'Payment_Name',
  PAYMENT_OPTION_NAME: 'Payment_Option_Name',
  PHONE: 'phone',
  PRICE_AFTER_DISCOUNT: 'Price_After_Discount',
  PRICE_BEFORE_DISCOUNT: 'Price_before_discount',
  PROCESSING_FEE: 'Processing_Fee',
  PRODUCT_NAME: 'name',
  PRODUCT_PRICE: 'price',
  PRODUCT_QUANTITY: 'quantity',
  PRODUCT_SKU: 'sku',
  RETURN_AIRLINE_NAMES: 'returnAirlineNames',
  RETURN_ARRIVAL_TIME: 'Return_Arrival_Time',
  RETURN_DATE: 'Return_Date',
  RETURN_DATE_WE: 'returnDateWE',
  RETURN_DEPARTURE_TIME: 'Return_Departure_Time',
  RETURN_FLIGHT_SELECTED: 'returnFlightSelected',
  RETURN_STOPS: 'returnStops',
  ROUTE: 'Sector',
  ROUTE_TYPE: 'Trip_Mode',
  SEARCH_DATE: 'Search_Date',
  SECTOR: 'Sector',
  SELECTED_DESTINATION_IATA: 'selectedDestinationIata',
  SELECTED_ORIGIN_IATA: 'selectedOriginIata',
  SELECTED_SEAT: 'selectedSeat',
  SESSION_ID: 'sessionId',
  SIGNUP_TYPE: 'SignupType',
  SUBSCRIBE_SIGNUP_TYPE: 'subscribeSignupType',
  TITLE: 'title',
  TOTAL_PRICE: 'totalPrice',
  TRANSACTION_ID: 'transactionId',
  TRANSACTION_PRODUCTS: 'transactionProducts',
  TRANSACTION_TAX: 'transactionTax',
  TRANSACTION_TOTAL: 'transactionTotal',
  TRAVELLER_ADULT: 'Adult',
  TRAVELLER_CHILD: 'Children',
  TRAVELLER_COUNT: 'Total_Pax',
  TRAVELLER_INFANT: 'Infant',
  TRIP_TYPE: 'Trip_Type',
  USER_ID: 'user_id',
  USER_TYPE: 'User_Type',
  VOUCHER_CODE: 'coupon',
  WHATSAPP_OPTIN: 'whatsappOptin',
  CORRELATION_ID : 'correlationId',
  BOARDING_TIME : 'Boarding_Time',
  LANDING_TIME : 'Landing_Time',
  RETURN_BOARDING_TIME : 'Return_Boarding_Time',
  RETURN_LANDING_TIME : 'Return_Landing_Time',
  STOPS : 'Stops',
  START_DATE : 'Start_date',
  AIRLINE : 'Airline',
  TOTAL_FARE : 'Total_Fare',
  BASE_FARE : 'Base_Fare',
  DAY_SEARCH : 'day_search',
  VIEW_DETAILS : 'view_details',
  PAX_TITLE: "PaxTitle",
  PAX_FIRSTNAME: "PaxFirstName",
  PAX_LASTNAME: "PaxLast Name",
  PHONE_NUMBER: "Phone Number",
  TICKET: "Ticket",
  T_API: "T_API",
  WHATAPP_OPTIN: "Whatapp_Optin",
  ONWARD_AIRLINE_NAME: "Onward_Airline_Name",
  RETURN_AIRLINE_NAME: "Return_Airline_Name",
  ONLINE_CHECK_IN : 'online_checkin',
  TRAVEL_INSURANCE : 'Travel_Insurance',
  MEDICAL_CANCELLATION : 'Medical_Cancellation',
  TERMS_CONDITIONS : 'TandC',
  PAYMENT_GATEWAY_NAME : 'PGName',
  COUPON_CODE : 'Coupon_Code',
  FROM_CITY : 'From_City',
  TO_CITY : 'To_City',
  BAGGAGE_CHECKED : 'Baggagechecked',
  THREE_D_SECURE : '3d_secure',
  SEATS : 'Seats',
  VAT : 'Vat',
  AIRLINECODE : 'AirlineCode',
  BOOKING_ID : 'Booking_id',
  SURNAME : 'Surname',
  FARE_DIFF : 'Fare_Diff',
  PAYMENT : 'Payment',
  COUNT : 'Count'
};
